import requests
import xml.etree.ElementTree as xml
import json

from .helpers import build_url, build_xml
from .validators import suggester, rev_geocoder, geocoder, check_addr
from .models import Object
from django import forms
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponse
from django.views.decorators.http import require_http_methods
from requests_oauthlib import OAuth1


@csrf_exempt
@require_http_methods("POST")
def create_point(request):
    try:
        data = (json.loads(request.body))
    except json.decoder.JSONDecodeError:
        return HttpResponseBadRequest('Wrong request count of fields - bad fields')
    if data.get('address') is None:
        return HttpResponseBadRequest('Wrong request count of fields - address')
    try:
        lat = float(data['lat'])
        lon = float(data['lon'])
    except KeyError:
        return HttpResponseBadRequest('Wrong request count of fields - lat, lon')
    except ValueError:
        return HttpResponseBadRequest('Wrong request types of data')

    address_obj = check_addr(data)
    if address_obj is None:
        return HttpResponseBadRequest('Wrong request address')

    user = request.user
    if user.is_authenticated:
        data = create_object(lat, lon, address_obj, user)
    else:
        data = create_note(lat, lon, address_obj)
    if not data['status_osm']:
        return HttpResponseBadRequest('Wrong request data - osm')
    data['status_db'] = send_db(lat, lon, address_obj, user)
    if not data['status_db']:
        return HttpResponseBadRequest('Wrong request data - db')
    return JsonResponse(data)


def create_note(lat, lon, address_obj):
    url = build_url(
        getattr(settings, 'OSM_URL'),
        getattr(settings, 'OSM_URL_NOTE'),
        {
            'lat': lat,
            'lon': lon,
            'text': address_obj['address'],
        }
    )
    response = requests.post(url)
    if not response.ok:
        return {'status_osm': False}
    data_json = {'status_osm': True}
    try:
        root = xml.fromstring(response.content)
        data_json['info'] = {}
        for child in root[0]:
            if child.tag != 'comments':
                data_json['info'][str(child.tag)] = child.text
    except (IndexError, xml.ParseError):
        return {'status_osm': False}
    return data_json


def create_object(lat, lon, address_obj, user):
    extra_data = user.social_auth.get(provider='openstreetmap').extra_data
    access_token = extra_data['access_token']
    address = address_obj['address_details']
    auth = OAuth1(
        getattr(settings, 'SOCIAL_AUTH_OPENSTREETMAP_KEY'),
        getattr(settings, 'SOCIAL_AUTH_OPENSTREETMAP_SECRET'),
        access_token['oauth_token'],
        access_token['oauth_token_secret']
    )

    url = build_url(
        getattr(settings, 'OSM_URL'),
        getattr(settings, 'OSM_URL_OBJECT_CREATE'),
    )
    data = build_xml({
        'osm': {
            'changeset': {
                '_tags_': {'version': '0.6', 'generator': 'iD'},
                'tag': {'_tags_': [
                    {'k': 'comment', 'v': 'SqS'},  # TODO field comment should be generated by users according OSM API
                    {'k': 'created_by', 'v': 'Open-FIAS v.1.0'},
                    {'k': 'host', 'v': 'https://open-fias.ru'},
                    {'k': 'locale', 'v': 'ru'},
                    {'k': 'changesets_count', 'v': '1'}
                ]}
            }
        }
    })
    response = requests.put(url, data=data, headers={"Content-Type": "text/xml"}, auth=auth)
    if not response.ok:
        return {'status_osm': False}
    commit_id = int(response.content)

    url = build_url(
        getattr(settings, 'OSM_URL'),
        getattr(settings, 'OSM_URL_OBJECT_UPLOAD').format(commit_id),
    )
    data = build_xml({
        'osmChange': {
            '_tags_': {'version': 0.6, 'generator': 'iD'},
            'create': {
                'node': {
                    '_tags_': {'id': -1, 'lon': lon, 'lat': lat, 'version': 0, 'changeset': commit_id},
                    'tag': {'_tags_': [
                        {'k': 'name', 'v': address_obj.get('name')},
                        {'k': 'addr:country', 'v': address.get('country')},
                        {'k': 'addr:region', 'v': address.get('region')},
                        {'k': 'addr:subregion', 'v': address.get('subregion')},
                        {'k': 'addr:city', 'v': address.get('locality')},
                        {'k': 'addr:suburb', 'v': address.get('suburb')},
                        {'k': 'addr:street', 'v': address.get('street')},
                        {'k': 'addr:housenumber', 'v': address.get('building')},
                        {'k': 'addr:postcode', 'v': address_obj.get('postalcode')}
                    ]}
                }
            },
            'modify': {},
            'delete': {
                '_tags_': {'if-unused': True}
            }
        }
    })
    response_info = requests.post(url, data=data.encode('utf-8'), headers={"Content-Type": "text/xml"}, auth=auth)
    if not response_info.ok:
        return {'status_osm': False}

    url = build_url(
        getattr(settings, 'OSM_URL'),
        getattr(settings, 'OSM_URL_OBJECT_CLOSE').format(commit_id),
    )
    response = requests.put(url, headers={"Content-Type": "text/xml"}, auth=auth)
    if not response.ok:
        return {'status_osm': False}
    data_json = {'status_osm': True}
    try:
        root = xml.fromstring(response_info.content)
        data_json['node'] = {}
        for child in root[0].attrib.items():
            data_json['node'][str(child[0])] = int(child[1])
    except (IndexError, xml.ParseError):
        return {'status_osm': False}
    return data_json


def send_db(lat, lon, address_obj, user):
    address_details = address_obj['address_details']
    form = ObjectForm(data=address_details)
    if form.is_valid():
        object_new = form.save(commit=False)
        object_new.latitude = float(lat)
        object_new.longitude = float(lon)
        if 'rank' in address_obj:
            object_new.rank = int(address_obj['rank'])
        if 'postalcode' in address_obj:
            object_new.postcode = int(address_obj['postalcode'])
        if user.is_authenticated:
            object_new.author = user
        object_new.save()
        return True
    return False


class ObjectForm(forms.ModelForm):
    class Meta:
        """Settings"""
        model = Object
        fields = [
            'name',
            'country',
            'region',
            'subregion',
            'locality',
            'suburb',
            'street',
            'building',
            'rank',
            'postcode',
        ]


@csrf_exempt
@require_http_methods("GET")
def get_suggest(request):
    data_json = suggester(request.GET)
    return JsonResponse(data_json)


@csrf_exempt
@require_http_methods("GET")
def get_geocoder(request):
    data_json = geocoder(request.GET)
    return JsonResponse(data_json)


@csrf_exempt
@require_http_methods("GET")
def get_rev_geocoder(request):
    data_json = rev_geocoder(request.GET)
    return JsonResponse(data_json)
