version: '2'


volumes:
    pgdata:
        driver: local

services:

    fias-nginx:
        restart: always
        image: nginx:latest
        expose:
            - 80
        ports:
            - "80:80"
        volumes:
            - ./src/static:/srv/www/fias_front/static
            - ./src/media:/srv/www/fias_front/media
            - ./src/logs:/srv/www/fias_front/logs
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - fias-react

    fias-react:
        restart: always
        build:
            context: .
            dockerfile: docker/react/Dockerfile
        volumes:
            - ./:/srv/www/fias_front/
        expose:
            - 3000
        ports:
            - 3000:3000
        command: "npm start"

