export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS';
export const GET_ADDRESS_START = 'GET_ADDRESS_START';
export const GET_ADDRESS_FAILED = 'GET_ADDRESS_FAILED';

export const GET_COORDS_SUCCESS = 'GET_COORDS_SUCCESS';
export const GET_COORDS_START = 'GET_COORDS_START';
export const GET_COORDS_FAILED = 'GET_COORDS_FAILED';

export const NEW_COORDS_PUTTED = 'NEW_COORDS_PUTTED';

export const SENDING_LINK_SUCCESS = 'SENDING_LINK_SUCCESS';
export const SENDING_LINK_START = 'SENDING_LINK_START';
export const SENDING_LINK_FAILED = 'SENDING_LINK_FAILED';

export const CLEAR_DATA = 'CLEAR_DATA';

export const UNFOCUS_INPUT = 'UNFOCUS_INPUT';

export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_MAP_COORDS = 'SET_MAP_COORDS';
export const SET_MARKER_COORDS = 'SET_MARKER_COORDS';

export const SUGGEST_START = 'SUGGEST_START';
export const SUGGEST_SUCCESS = 'SUGGEST_SUCCESS';
export const SUGGEST_FAILED = 'SUGGEST_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const SET_NEW_POINTS = 'SET_NEW_POINTS';

export const GET_STATS_SUCCESS = 'GET_STATS_SUCCESS';
export const GET_STATS_START = 'GET_STATS_START';
export const GET_STATS_FAILED = 'GET_STATS_FAILED';
export const ADD_NEW_POINT_TO_STATS = 'ADD_NEW_POINT_TO_STATS';