version: '2'


volumes:
    pgdata:
        driver: local

services:

    fias-nginx:
        restart: always
        image: nginx:latest
        expose:
            - 8080
        ports:
            - 8081:8080
        volumes:
            - ./src/static:/srv/www/fias_back/static
            - ./src/media:/srv/www/fias_back/media
            - ./src/logs:/srv/www/fias_back/logs
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - fias-python
            - fias-centrifugo

    fias-python:
        restart: always
        build:
            context: .
            dockerfile: docker/python/Dockerfile
        volumes:
            - ./src:/srv/www/fias_back
        expose:
            - 8000
        ports:
            - 8001:8000
        command: "gunicorn -c gunicorn.py open_fias.wsgi"

        environment:
          DB_NAME: ${DB_NAME}
          DB_HOST: ${DB_HOST}
          DB_USER: ${DB_USER}
          DB_PASSWORD: ${DB_PASSWORD}

          CENT_SECRET: ${CENT_SECRET}
          CENT_ADMIN_PASSWORD: ${CENT_ADMIN_PASSWORD}
          CENT_ADMIN_SECRET: ${CENT_ADMIN_SECRET}
          CENT_API_KEY: ${CENT_API_KEY}

        depends_on:
            - fias-postgres
            - fias-centrifugo

        links:
            - fias-memcached

    fias-postgres:
        image: postgres:latest
        ports:
            - 6001:5432
        environment:
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_DB: ${DB_NAME}
          PGDATA: /var/lib/postgresql/data
        volumes:
            - .sql_data:/var/lib/postgresql/data

    fias-centrifugo:
        image: centrifugo/centrifugo:latest
        command: centrifugo -c /config.json --admin
        environment:
          CENTRIFUGO_SECRET: ${CENT_SECRET}
          CENTRIFUGO_ADMIN_PASSWORD: ${CENT_ADMIN_PASSWORD}
          CENTRIFUGO_ADMIN_SECRET: ${CENT_ADMIN_SECRET}
          CENTRIFUGO_API_KEY: ${CENT_API_KEY}
        volumes:
            - ./docker/centrifugo/centrifugo.json:/config.json
        restart: always
        ports:
            - 9001:9000
        ulimits:
          nofile:
            soft: 65536
            hard: 65536

    fias-memcached:
        image: memcached
        ports:
            - 11212:11211
        entrypoint:
            - memcached
            - -m 64

networks:                                
  default:                               
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: 1450

