# Generated by Django 2.1.7 on 2019-04-01 18:11

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='имя объекта')),
                ('is_archive', models.BooleanField(default=False, verbose_name='объект в архиве')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('fias_guid', models.UUIDField(null=True)),
                ('fias_id', models.IntegerField(null=True)),
                ('note_id', models.IntegerField(null=True)),
                ('changeset_id', models.IntegerField(null=True)),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('address', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='адрес')),
                ('fias_level', models.CharField(blank=True, max_length=2, verbose_name='уровень адресного объекта')),
                ('postalcode', models.TextField(blank=True, verbose_name='почтовый индекс')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maps', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['name'],
            },
        ),
    ]
