# Generated by Django 2.1.7 on 2019-04-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20190401_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='fias_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
