# Generated by Django 2.1.7 on 2019-05-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20190401_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='долгота'),
        ),
    ]
