# Generated by Django 2.1.7 on 2019-05-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20190518_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='postalcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='почтовый индекс'),
        ),
    ]
