# Generated by Django 2.1.7 on 2019-05-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20190518_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='object',
            name='fias_id',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='is_archive',
            field=models.BooleanField(db_index=True, default=False, verbose_name='объект в архиве'),
        ),
        migrations.AlterIndexTogether(
            name='object',
            index_together={('note_id', 'changeset_id')},
        ),
    ]
